slide_1:
  title: 'Agile Consulting'
  description: 'We perform product audit, process configuration and automation, improve quality and productivity.'
slide_2:
  title: 'Web Development'
  description: 'We passionate into elegant solution for your web project using RubyOnRails, React and more.'
slide_3:
  title: 'Mobile Development'
  description: 'We build applications for mobile, from highly technical internal tools to robust customer facing interfaces.'
