slide_web:
  title: 'Web Development'
  description: 'We bring elegant solutions into your web projects using Ruby on Rails, Vue.js, React.js, and more.'
slide_mobile:
  title: 'Mobile Development'
  description: 'We build applications for mobile, from highly technical internal tools to robust customer-facing interfaces.'
slide_rails:
  title: 'Ruby on Rails'
  description: 'Using Ruby on Rails, we can instantly bring reliable products onto the market.'
slide_react:
  title: 'React Native'
  description: 'React Native allows us to quickly ship mobile apps faster while maintaining a world-class mobile user experience.'
