items:
  - title: Web Development
    description: We bring elegant solutions into your web projects using Ruby on Rails, Vue.js, React.js, and more.
  - title: Mobile Development
    description: We build applications for mobile, from highly technical internal tools to robust customer-facing interfaces.
  - title: Ruby on Rails
    description: Using Ruby on Rails, we can instantly bring reliable products onto the market.
  - title: React Native
    description: React Native allows us to build mobile apps faster while maintaining world-class mobile user experience.
