# config.yml

backend:
  name: git-gateway
  branch: develop
media_folder: 'assets/'
collections:
  - name: 'main_screen_posts'
    label: 'Main Screen Posts'
    folder: '_data/main_screen_posts'
    fields:
      - name: 'items'
        label: 'Items'
        widget: 'list'
        fields:
          - { name: title, label: Title, widget: string }
          - { name: url, label: Url, widget: string }
          - { name: author, label: Author, widget: string }
          - { name: image, label: Image, widget: string }
          - { name: datePublished, label: DatePublished, widget: string }
          - name: publisher
            label: Publisher
            widget: string
            fields:
              - { name: name, label: Name, widget: string }
              - { name: url, label: Url, widget: string }
          - { name: mainEntityOfPage, label: MainEntityOfPage, widget: string }
  - name: 'use_cases'
    label: 'Use Cases'
    folder: '_data/use_cases'
    fields:
      - name: 'items'
        label: 'Items'
        widget: 'list'
        fields:
          - { name: title, label: Title, widget: string }
          - { name: scope, label: Scope, widget: string }
          - { name: desc, label: Desc, widget: string }
          - { name: url, label: Url, widget: string }
  - name: 'services'
    label: 'Services'
    folder: '_data/services'
    fields:
      - name: 'items'
        label: 'Items'
        widget: 'list'
        fields:
          - { name: title, label: Title, widget: string }
          - { name: description, label: Description, widget: string }
  - name: 'posts'
    label: 'Posts'
    folder: '_data/posts'
    fields:
      - name: 'items'
        label: 'Items'
        widget: 'list'
        fields:
          - { name: title, label: Title, widget: string }
          - { name: url, label: Url, widget: string }
          - { name: author, label: Author, widget: string }
          - { name: image, label: Image, widget: string }
          - { name: datePublished, label: DatePublished, widget: string }
          - name: publisher
            label: Publisher
            widget: string
            fields:
              - { name: name, label: Name, widget: string }
              - { name: url, label: Url, widget: string }
          - { name: mainEntityOfPage, label: MainEntityOfPage, widget: string }
  - name: 'socials'
    label: 'Socials'
    folder: '_data/socials'
    fields:
      - name: 'items'
        label: 'Items'
        widget: 'list'
        fields:
          - { name: title, label: Title, widget: string }
          - { name: url, label: Url, widget: string }
